### ISSUE TITLE
numba-dppy extension

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba#76]
Reorganize code base and initial version of numba-dppy extension
- Move the `numba.dppl` package to its own repository (i.e. `numba-dppy`)
- All core Numba changes to be outlined as patches needed to build Numba with numba-dppy
- All patches need to be analyzed if they can be refactored or converted into plugins

PRs for **cleaning** unintended changes (make branch `pydppl` as close as possible to `release0.51` branch):
- [x] #84 @reazulhoque 
  - [x] #89 @PokhodenkoSA  
- [x] #90 @reazulhoque @1e-to closes #89
- [x] #108 @reazulhoque 
- [x] #86 @Hardcode84 @reazulhoque 
- [x] #88 @reazulhoque 
- [x] #85 @DrTodd13
- [x] #104 @DrTodd13 @reazulhoque - reviewed - most debug code to remove, 2 possible upstream PRs (1 as minimum).
  - [x] numba#6466
- [x] #100 @reazulhoque @diptorupd - reviewed - need to be tested
  - [x] https://github.com/IntelPython/numba-dppy/pull/6
- [x] #87 @DrTodd13 @reazulhoque - reviewed - need to test and remove
- [x] #101 @reazulhoque - reviewed - need investigation and could be removed after tests

PRs with patches (after refactoring it could be proposed to **upstream**, it is for starting discussion about this changes):
- [ ] #96 @AlexanderKalistratov @1e-to 
  - [x] #118 @PokhodenkoSA - update for moving to `numba-dppy`
  - [ ] https://github.com/numba/numba/pull/6870 (or https://github.com/numba/numba/pull/6770)
  - [ ] https://github.com/IntelPython/numba-dppy/pull/278
    - https://github.com/IntelPython/numba-dppy/issues/271 - update numba-dppy to new solution
  - [ ] https://github.com/numba/numba/pull/6899
- [x] #98 @reazulhoque @AlexanderKalistratov @DrTodd13 - reviewed - redesign and upstream
  - [x] https://github.com/numba/numba/pull/6880
  - [ ] https://github.com/IntelPython/numba/pull/215
  - [ ] https://github.com/IntelPython/numba/issues/177
- [x] #99 @reazulhoque - reviewed - redesign and upstream - 2 separate changes
  - [x] numba#6467
  - [x] numba#6468
- [x] #92 @DrTodd13 @reazulhoque - reviewed - discussion and upstream
  - [x] numba#6469
- [ ] #139 (#116) @DrTodd13 @PokhodenkoSA
  - [ ] numba#6148
- [x] #135 (f.k.a. #130) @1e-to @PokhodenkoSA - could be upstreamed
  - [x] https://github.com/numba/numba/pull/6545

All upstream patches has label https://github.com/numba/numba/labels/dpPy.

PRs which should me **moved** to `numba-dppy` package:
- [x] #102 @PokhodenkoSA - reviewed with @reazulhoque 
- [x] #109 @PokhodenkoSA - reviewed with @reazulhoque 
- [x] #110 @PokhodenkoSA - reviewed with @reazulhoque  
- [x] #107 @PokhodenkoSA - reviewed with @reazulhoque 
- [x] #103 @PokhodenkoSA - reviewed with @reazulhoque 
- [x] #106 @PokhodenkoSA @reazulhoque - reviewed - remove code, design error handling in `numba-dppy`
  - [x] https://github.com/IntelPython/numba-dppy/pull/14
- [x] #93 @PokhodenkoSA @reazulhoque - reviewed - need to be moved
  - [x] https://github.com/IntelPython/numba-dppy/pull/15
- [x] #111 @PokhodenkoSA - moving `numba/dppl` - delete it after all other PRs
  - [x] https://github.com/IntelPython/numba-dppy/pull/2
  - [x] #117 
- [x] #105 @DrTodd13 @AlexanderKalistratov @reazulhoque - reviewed - remove it but need work prior apply
  - [x] https://github.com/IntelPython/numba-dppy/issues/30
  - [x] https://github.com/IntelPython/numba-dppy/pull/46
- [ ] #120 @reazulhoque @DrTodd13 - need fixes in `numba-dppy`

Process current PRs to numba:
- [x] #119 @akharche - moved to IntelPython/numba-dppy#27
- [x] #116 @DrTodd13 @PokhodenkoSA - move part to `numba-dppy`
  - [x] IntelPython/numba-dppy#50

Patched version: https://github.com/IntelPython/numba/pull/124

How to see our changes: `git diff release0.51..pydppl`

# Recommended way of development now:
1. Create conda environment
2. Clone https://github.com/IntelPython/dpctl from branch [master](https://github.com/IntelPython/dpctl/tree/master). Call: `python setup.py develop`.
3. Clone https://github.com/IntelPython/numba from branch [patched](https://github.com/IntelPython/numba/tree/patched). Call: `python setup.py develop`.
4. Clone https://github.com/IntelPython/numba-dppy from branch [main](https://github.com/IntelPython/numba-dppy/tree/main). Call: `python setup.py develop`.
5. Install required conda packages if `python setup.py develop` shows that some packages are not installed.

# Branches status

1. `patched` - contains `release0.51` branch, minimal set of patches.
2. `pydppl` - contains all history, code similar to `patched`, `numba-dppy` subtree.
3. `clean` - contains all history, all patches removed, `numba-dppy` subtree removed - code the same as `release0.51`
4. `patched-history` - contains `clean`, minimal set of patches.

You should target your PRs to `patched` branch, because it is simpler than `pydppl` but contains the same code.

**Comment by PokhodenkoSA** [comment]
Related #51 - closed by #86.

**Comment by PokhodenkoSA** [comment]
From @diptorupd:
- What if `dpCtl` is installed and `numba-dppy` is not?
- How `numba-dppy` will understand that `IntelPython/numba` is installed?

**Comment by PokhodenkoSA** [comment]
I need a way to build new package with all modifications (i.e. removing `numba.dppl` folder) but make it different from packages we build before. Build number I think is not visible enough. Using next version 0.51.3 loses connection to base Numba version. Using 0.51.2rc1 is also not related to upstream version. Possibly, introducing new end number 0.51.2.1 is ok. Also it is pretty close in goal to buildnumber but more visible.

**Comment by PokhodenkoSA** [comment]
> a way to build new package with all modifications (i.e. removing `numba.dppl` folder) but make it different from packages we build before

We decided to use build number which is significantly different from previous one. I.e. use build number 20 when the last one was 12.

**Comment by reazulhoque** [comment]
Update:

PRs with patches (after refactoring it could be proposed to **upstream**, it is for starting discussion about this changes):
- [ ] #96 @AlexanderKalistratov 
  - [x] #118 @PokhodenkoSA - update for moving to `numba-dppy`
  - [ ] https://github.com/IntelPython/numba/issues/176
- [ ] #98 @reazulhoque @AlexanderKalistratov @DrTodd13 - reviewed - redesign and upstream
  - [ ] https://github.com/IntelPython/numba/issues/177 
- [ ] #99 @reazulhoque - reviewed - redesign and upstream - 2 separate changes
  - [ ] numba#6467
    - [ ] https://github.com/IntelPython/numba/issues/178
  - [ ] numba#6468
    - [ ] https://github.com/IntelPython/numba/issues/179
- [ ] #92 @DrTodd13 @reazulhoque - reviewed - discussion and upstream
  - [ ] numba#6469
    - [ ] https://github.com/IntelPython/numba/issues/180 
- [ ] #139 (#116) @DrTodd13 @PokhodenkoSA
  - [ ] numba#6148
- [x] #135 (f.k.a. #130) @1e-to @PokhodenkoSA - could be upstreamed
  - [x] https://github.com/numba/numba/pull/6545

**Comment by PokhodenkoSA** [comment]
@reazulhoque why did you decide to make a copy of part of description and do not modify description itself?

**Comment by reazulhoque** [comment]
I intended to update the ticket. Modifying the descripton would change the original and stops from keeping versions and updates separate.
